/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import java.util.*;
import nisse.analysis.*;

@SuppressWarnings("nls")
public final class AEndblock extends PEndblock
{
    private TEndkwd _endkwd_;
    private PBeblock _beblock_;
    private final LinkedList<TEol> _eol_ = new LinkedList<TEol>();

    public AEndblock()
    {
        // Constructor
    }

    public AEndblock(
        @SuppressWarnings("hiding") TEndkwd _endkwd_,
        @SuppressWarnings("hiding") PBeblock _beblock_,
        @SuppressWarnings("hiding") List<TEol> _eol_)
    {
        // Constructor
        setEndkwd(_endkwd_);

        setBeblock(_beblock_);

        setEol(_eol_);

    }

    @Override
    public Object clone()
    {
        return new AEndblock(
            cloneNode(this._endkwd_),
            cloneNode(this._beblock_),
            cloneList(this._eol_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEndblock(this);
    }

    public TEndkwd getEndkwd()
    {
        return this._endkwd_;
    }

    public void setEndkwd(TEndkwd node)
    {
        if(this._endkwd_ != null)
        {
            this._endkwd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endkwd_ = node;
    }

    public PBeblock getBeblock()
    {
        return this._beblock_;
    }

    public void setBeblock(PBeblock node)
    {
        if(this._beblock_ != null)
        {
            this._beblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._beblock_ = node;
    }

    public LinkedList<TEol> getEol()
    {
        return this._eol_;
    }

    public void setEol(List<TEol> list)
    {
        this._eol_.clear();
        this._eol_.addAll(list);
        for(TEol e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._endkwd_)
            + toString(this._beblock_)
            + toString(this._eol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._endkwd_ == child)
        {
            this._endkwd_ = null;
            return;
        }

        if(this._beblock_ == child)
        {
            this._beblock_ = null;
            return;
        }

        if(this._eol_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._endkwd_ == oldChild)
        {
            setEndkwd((TEndkwd) newChild);
            return;
        }

        if(this._beblock_ == oldChild)
        {
            setBeblock((PBeblock) newChild);
            return;
        }

        for(ListIterator<TEol> i = this._eol_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TEol) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
