/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class ANumerationLines extends PLines
{
    private PNumeration _numeration_;

    public ANumerationLines()
    {
        // Constructor
    }

    public ANumerationLines(
        @SuppressWarnings("hiding") PNumeration _numeration_)
    {
        // Constructor
        setNumeration(_numeration_);

    }

    @Override
    public Object clone()
    {
        return new ANumerationLines(
            cloneNode(this._numeration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumerationLines(this);
    }

    public PNumeration getNumeration()
    {
        return this._numeration_;
    }

    public void setNumeration(PNumeration node)
    {
        if(this._numeration_ != null)
        {
            this._numeration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeration_ == child)
        {
            this._numeration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeration_ == oldChild)
        {
            setNumeration((PNumeration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
