/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class ASettingBlocks extends PBlocks
{
    private PSettingblock _settingblock_;

    public ASettingBlocks()
    {
        // Constructor
    }

    public ASettingBlocks(
        @SuppressWarnings("hiding") PSettingblock _settingblock_)
    {
        // Constructor
        setSettingblock(_settingblock_);

    }

    @Override
    public Object clone()
    {
        return new ASettingBlocks(
            cloneNode(this._settingblock_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASettingBlocks(this);
    }

    public PSettingblock getSettingblock()
    {
        return this._settingblock_;
    }

    public void setSettingblock(PSettingblock node)
    {
        if(this._settingblock_ != null)
        {
            this._settingblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._settingblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._settingblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._settingblock_ == child)
        {
            this._settingblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._settingblock_ == oldChild)
        {
            setSettingblock((PSettingblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
