/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class TSettingkwd extends Token
{
    public TSettingkwd()
    {
        super.setText("@setting");
    }

    public TSettingkwd(int line, int pos)
    {
        super.setText("@setting");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSettingkwd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSettingkwd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSettingkwd text.");
    }
}
