/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.analysis;

import java.util.*;
import nisse.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseANisse(ANisse node)
    {
        defaultCase(node);
    }

    public void caseABlockBlocks(ABlockBlocks node)
    {
        defaultCase(node);
    }

    public void caseASettingBlocks(ASettingBlocks node)
    {
        defaultCase(node);
    }

    public void caseASettingLines(ASettingLines node)
    {
        defaultCase(node);
    }

    public void caseANumerationLines(ANumerationLines node)
    {
        defaultCase(node);
    }

    public void caseAItemlistLines(AItemlistLines node)
    {
        defaultCase(node);
    }

    public void caseAPlaintextLines(APlaintextLines node)
    {
        defaultCase(node);
    }

    public void caseANumeration(ANumeration node)
    {
        defaultCase(node);
    }

    public void caseAPlaintextNumerationv1(APlaintextNumerationv1 node)
    {
        defaultCase(node);
    }

    public void caseANumerationNumerationv1(ANumerationNumerationv1 node)
    {
        defaultCase(node);
    }

    public void caseAItemlist(AItemlist node)
    {
        defaultCase(node);
    }

    public void caseAPlaintextItemlistv1(APlaintextItemlistv1 node)
    {
        defaultCase(node);
    }

    public void caseAItemlistItemlistv1(AItemlistItemlistv1 node)
    {
        defaultCase(node);
    }

    public void caseABeginblock(ABeginblock node)
    {
        defaultCase(node);
    }

    public void caseAEndblock(AEndblock node)
    {
        defaultCase(node);
    }

    public void caseABeblock(ABeblock node)
    {
        defaultCase(node);
    }

    public void caseABeblockv1(ABeblockv1 node)
    {
        defaultCase(node);
    }

    public void caseASettingblock(ASettingblock node)
    {
        defaultCase(node);
    }

    public void caseAPlains(APlains node)
    {
        defaultCase(node);
    }

    public void caseAShortblockPlainsv1(AShortblockPlainsv1 node)
    {
        defaultCase(node);
    }

    public void caseACharallPlainsv1(ACharallPlainsv1 node)
    {
        defaultCase(node);
    }

    public void caseAShortblock(AShortblock node)
    {
        defaultCase(node);
    }

    public void caseAShortblockv1(AShortblockv1 node)
    {
        defaultCase(node);
    }

    public void caseAShortidents(AShortidents node)
    {
        defaultCase(node);
    }

    public void caseAShortident(AShortident node)
    {
        defaultCase(node);
    }

    public void caseACharShortidentv1(ACharShortidentv1 node)
    {
        defaultCase(node);
    }

    public void caseADigitShortidentv1(ADigitShortidentv1 node)
    {
        defaultCase(node);
    }

    public void caseAFloatShortidentv1(AFloatShortidentv1 node)
    {
        defaultCase(node);
    }

    public void caseAColonShortidentv1(AColonShortidentv1 node)
    {
        defaultCase(node);
    }

    public void caseAFslashShortidentv1(AFslashShortidentv1 node)
    {
        defaultCase(node);
    }

    public void caseAAtKwd(AAtKwd node)
    {
        defaultCase(node);
    }

    public void caseAUrlKwd(AUrlKwd node)
    {
        defaultCase(node);
    }

    public void caseAColonCharall(AColonCharall node)
    {
        defaultCase(node);
    }

    public void caseADigitCharall(ADigitCharall node)
    {
        defaultCase(node);
    }

    public void caseASemicolonCharall(ASemicolonCharall node)
    {
        defaultCase(node);
    }

    public void caseAPercentCharall(APercentCharall node)
    {
        defaultCase(node);
    }

    public void caseAForwardslashCharall(AForwardslashCharall node)
    {
        defaultCase(node);
    }

    public void caseABackslashCharall(ABackslashCharall node)
    {
        defaultCase(node);
    }

    public void caseAExclamationCharall(AExclamationCharall node)
    {
        defaultCase(node);
    }

    public void caseAMorecharCharall(AMorecharCharall node)
    {
        defaultCase(node);
    }

    public void caseACharCharall(ACharCharall node)
    {
        defaultCase(node);
    }

    public void caseASpaceCharall(ASpaceCharall node)
    {
        defaultCase(node);
    }

    public void caseTFormatKwd(TFormatKwd node)
    {
        defaultCase(node);
    }

    public void caseTUrl(TUrl node)
    {
        defaultCase(node);
    }

    public void caseTSpace(TSpace node)
    {
        defaultCase(node);
    }

    public void caseTSettingkwd(TSettingkwd node)
    {
        defaultCase(node);
    }

    public void caseTBeginkwd(TBeginkwd node)
    {
        defaultCase(node);
    }

    public void caseTEndkwd(TEndkwd node)
    {
        defaultCase(node);
    }

    public void caseTAtsign(TAtsign node)
    {
        defaultCase(node);
    }

    public void caseTLcurly(TLcurly node)
    {
        defaultCase(node);
    }

    public void caseTRcurly(TRcurly node)
    {
        defaultCase(node);
    }

    public void caseTPipe(TPipe node)
    {
        defaultCase(node);
    }

    public void caseTFslash(TFslash node)
    {
        defaultCase(node);
    }

    public void caseTBslash(TBslash node)
    {
        defaultCase(node);
    }

    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    public void caseTScolon(TScolon node)
    {
        defaultCase(node);
    }

    public void caseTBlist(TBlist node)
    {
        defaultCase(node);
    }

    public void caseTNlist(TNlist node)
    {
        defaultCase(node);
    }

    public void caseTPercent(TPercent node)
    {
        defaultCase(node);
    }

    public void caseTExclamation(TExclamation node)
    {
        defaultCase(node);
    }

    public void caseTEol(TEol node)
    {
        defaultCase(node);
    }

    public void caseTChar(TChar node)
    {
        defaultCase(node);
    }

    public void caseTDigit(TDigit node)
    {
        defaultCase(node);
    }

    public void caseTFloat(TFloat node)
    {
        defaultCase(node);
    }

    public void caseTMorechar(TMorechar node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
