/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AAttributetestPartPart extends PAttributetestPartPart
{
    private TComma _comma_;
    private PTypename _typename_;

    public AAttributetestPartPart()
    {
        // Constructor
    }

    public AAttributetestPartPart(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PTypename _typename_)
    {
        // Constructor
        setComma(_comma_);

        setTypename(_typename_);

    }

    @Override
    public Object clone()
    {
        return new AAttributetestPartPart(
            cloneNode(this._comma_),
            cloneNode(this._typename_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributetestPartPart(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PTypename getTypename()
    {
        return this._typename_;
    }

    public void setTypename(PTypename node)
    {
        if(this._typename_ != null)
        {
            this._typename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typename_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._typename_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._typename_ == child)
        {
            this._typename_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._typename_ == oldChild)
        {
            setTypename((PTypename) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
