/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AAttributetest extends PAttributetest
{
    private TAxisAttribute _axisAttribute_;
    private TLparenth _lparenth_;
    private PAttributetestPart _attributetestPart_;
    private TRparenth _rparenth_;

    public AAttributetest()
    {
        // Constructor
    }

    public AAttributetest(
        @SuppressWarnings("hiding") TAxisAttribute _axisAttribute_,
        @SuppressWarnings("hiding") TLparenth _lparenth_,
        @SuppressWarnings("hiding") PAttributetestPart _attributetestPart_,
        @SuppressWarnings("hiding") TRparenth _rparenth_)
    {
        // Constructor
        setAxisAttribute(_axisAttribute_);

        setLparenth(_lparenth_);

        setAttributetestPart(_attributetestPart_);

        setRparenth(_rparenth_);

    }

    @Override
    public Object clone()
    {
        return new AAttributetest(
            cloneNode(this._axisAttribute_),
            cloneNode(this._lparenth_),
            cloneNode(this._attributetestPart_),
            cloneNode(this._rparenth_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributetest(this);
    }

    public TAxisAttribute getAxisAttribute()
    {
        return this._axisAttribute_;
    }

    public void setAxisAttribute(TAxisAttribute node)
    {
        if(this._axisAttribute_ != null)
        {
            this._axisAttribute_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisAttribute_ = node;
    }

    public TLparenth getLparenth()
    {
        return this._lparenth_;
    }

    public void setLparenth(TLparenth node)
    {
        if(this._lparenth_ != null)
        {
            this._lparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lparenth_ = node;
    }

    public PAttributetestPart getAttributetestPart()
    {
        return this._attributetestPart_;
    }

    public void setAttributetestPart(PAttributetestPart node)
    {
        if(this._attributetestPart_ != null)
        {
            this._attributetestPart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributetestPart_ = node;
    }

    public TRparenth getRparenth()
    {
        return this._rparenth_;
    }

    public void setRparenth(TRparenth node)
    {
        if(this._rparenth_ != null)
        {
            this._rparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rparenth_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._axisAttribute_)
            + toString(this._lparenth_)
            + toString(this._attributetestPart_)
            + toString(this._rparenth_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._axisAttribute_ == child)
        {
            this._axisAttribute_ = null;
            return;
        }

        if(this._lparenth_ == child)
        {
            this._lparenth_ = null;
            return;
        }

        if(this._attributetestPart_ == child)
        {
            this._attributetestPart_ = null;
            return;
        }

        if(this._rparenth_ == child)
        {
            this._rparenth_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._axisAttribute_ == oldChild)
        {
            setAxisAttribute((TAxisAttribute) newChild);
            return;
        }

        if(this._lparenth_ == oldChild)
        {
            setLparenth((TLparenth) newChild);
            return;
        }

        if(this._attributetestPart_ == oldChild)
        {
            setAttributetestPart((PAttributetestPart) newChild);
            return;
        }

        if(this._rparenth_ == oldChild)
        {
            setRparenth((TRparenth) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
