/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AAttributeKindtest extends PKindtest
{
    private PAttributetest _attributetest_;

    public AAttributeKindtest()
    {
        // Constructor
    }

    public AAttributeKindtest(
        @SuppressWarnings("hiding") PAttributetest _attributetest_)
    {
        // Constructor
        setAttributetest(_attributetest_);

    }

    @Override
    public Object clone()
    {
        return new AAttributeKindtest(
            cloneNode(this._attributetest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributeKindtest(this);
    }

    public PAttributetest getAttributetest()
    {
        return this._attributetest_;
    }

    public void setAttributetest(PAttributetest node)
    {
        if(this._attributetest_ != null)
        {
            this._attributetest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributetest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributetest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributetest_ == child)
        {
            this._attributetest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributetest_ == oldChild)
        {
            setAttributetest((PAttributetest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
