/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultattname extends PDefaultattname
{
    private TXmlns _xmlns_;

    public ADefaultattname()
    {
        // Constructor
    }

    public ADefaultattname(
        @SuppressWarnings("hiding") TXmlns _xmlns_)
    {
        // Constructor
        setXmlns(_xmlns_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultattname(
            cloneNode(this._xmlns_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultattname(this);
    }

    public TXmlns getXmlns()
    {
        return this._xmlns_;
    }

    public void setXmlns(TXmlns node)
    {
        if(this._xmlns_ != null)
        {
            this._xmlns_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xmlns_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._xmlns_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._xmlns_ == child)
        {
            this._xmlns_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._xmlns_ == oldChild)
        {
            setXmlns((TXmlns) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
