/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ADocumentKindtest extends PKindtest
{
    private PDocumenttest _documenttest_;

    public ADocumentKindtest()
    {
        // Constructor
    }

    public ADocumentKindtest(
        @SuppressWarnings("hiding") PDocumenttest _documenttest_)
    {
        // Constructor
        setDocumenttest(_documenttest_);

    }

    @Override
    public Object clone()
    {
        return new ADocumentKindtest(
            cloneNode(this._documenttest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADocumentKindtest(this);
    }

    public PDocumenttest getDocumenttest()
    {
        return this._documenttest_;
    }

    public void setDocumenttest(PDocumenttest node)
    {
        if(this._documenttest_ != null)
        {
            this._documenttest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._documenttest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._documenttest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._documenttest_ == child)
        {
            this._documenttest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._documenttest_ == oldChild)
        {
            setDocumenttest((PDocumenttest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
