/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AForwardaxisPartOne extends PForwardaxisPartOne
{
    private TAxisChild _axisChild_;
    private TAxisDelim _axisDelim_;

    public AForwardaxisPartOne()
    {
        // Constructor
    }

    public AForwardaxisPartOne(
        @SuppressWarnings("hiding") TAxisChild _axisChild_,
        @SuppressWarnings("hiding") TAxisDelim _axisDelim_)
    {
        // Constructor
        setAxisChild(_axisChild_);

        setAxisDelim(_axisDelim_);

    }

    @Override
    public Object clone()
    {
        return new AForwardaxisPartOne(
            cloneNode(this._axisChild_),
            cloneNode(this._axisDelim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForwardaxisPartOne(this);
    }

    public TAxisChild getAxisChild()
    {
        return this._axisChild_;
    }

    public void setAxisChild(TAxisChild node)
    {
        if(this._axisChild_ != null)
        {
            this._axisChild_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisChild_ = node;
    }

    public TAxisDelim getAxisDelim()
    {
        return this._axisDelim_;
    }

    public void setAxisDelim(TAxisDelim node)
    {
        if(this._axisDelim_ != null)
        {
            this._axisDelim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisDelim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._axisChild_)
            + toString(this._axisDelim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._axisChild_ == child)
        {
            this._axisChild_ = null;
            return;
        }

        if(this._axisDelim_ == child)
        {
            this._axisDelim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._axisChild_ == oldChild)
        {
            setAxisChild((TAxisChild) newChild);
            return;
        }

        if(this._axisDelim_ == oldChild)
        {
            setAxisDelim((TAxisDelim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
