/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AForwardAxisstepPart extends PAxisstepPart
{
    private PForwardstep _forwardstep_;

    public AForwardAxisstepPart()
    {
        // Constructor
    }

    public AForwardAxisstepPart(
        @SuppressWarnings("hiding") PForwardstep _forwardstep_)
    {
        // Constructor
        setForwardstep(_forwardstep_);

    }

    @Override
    public Object clone()
    {
        return new AForwardAxisstepPart(
            cloneNode(this._forwardstep_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForwardAxisstepPart(this);
    }

    public PForwardstep getForwardstep()
    {
        return this._forwardstep_;
    }

    public void setForwardstep(PForwardstep node)
    {
        if(this._forwardstep_ != null)
        {
            this._forwardstep_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forwardstep_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forwardstep_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forwardstep_ == child)
        {
            this._forwardstep_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forwardstep_ == oldChild)
        {
            setForwardstep((PForwardstep) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
