/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AForward1Forwardaxis extends PForwardaxis
{
    private PForwardaxisPartOne _forwardaxisPartOne_;

    public AForward1Forwardaxis()
    {
        // Constructor
    }

    public AForward1Forwardaxis(
        @SuppressWarnings("hiding") PForwardaxisPartOne _forwardaxisPartOne_)
    {
        // Constructor
        setForwardaxisPartOne(_forwardaxisPartOne_);

    }

    @Override
    public Object clone()
    {
        return new AForward1Forwardaxis(
            cloneNode(this._forwardaxisPartOne_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForward1Forwardaxis(this);
    }

    public PForwardaxisPartOne getForwardaxisPartOne()
    {
        return this._forwardaxisPartOne_;
    }

    public void setForwardaxisPartOne(PForwardaxisPartOne node)
    {
        if(this._forwardaxisPartOne_ != null)
        {
            this._forwardaxisPartOne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forwardaxisPartOne_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forwardaxisPartOne_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forwardaxisPartOne_ == child)
        {
            this._forwardaxisPartOne_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forwardaxisPartOne_ == oldChild)
        {
            setForwardaxisPartOne((PForwardaxisPartOne) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
