/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AForwardaxisPartEight extends PForwardaxisPartEight
{
    private TAxisNamespace _axisNamespace_;
    private TAxisDelim _axisDelim_;

    public AForwardaxisPartEight()
    {
        // Constructor
    }

    public AForwardaxisPartEight(
        @SuppressWarnings("hiding") TAxisNamespace _axisNamespace_,
        @SuppressWarnings("hiding") TAxisDelim _axisDelim_)
    {
        // Constructor
        setAxisNamespace(_axisNamespace_);

        setAxisDelim(_axisDelim_);

    }

    @Override
    public Object clone()
    {
        return new AForwardaxisPartEight(
            cloneNode(this._axisNamespace_),
            cloneNode(this._axisDelim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForwardaxisPartEight(this);
    }

    public TAxisNamespace getAxisNamespace()
    {
        return this._axisNamespace_;
    }

    public void setAxisNamespace(TAxisNamespace node)
    {
        if(this._axisNamespace_ != null)
        {
            this._axisNamespace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisNamespace_ = node;
    }

    public TAxisDelim getAxisDelim()
    {
        return this._axisDelim_;
    }

    public void setAxisDelim(TAxisDelim node)
    {
        if(this._axisDelim_ != null)
        {
            this._axisDelim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisDelim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._axisNamespace_)
            + toString(this._axisDelim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._axisNamespace_ == child)
        {
            this._axisNamespace_ = null;
            return;
        }

        if(this._axisDelim_ == child)
        {
            this._axisDelim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._axisNamespace_ == oldChild)
        {
            setAxisNamespace((TAxisNamespace) newChild);
            return;
        }

        if(this._axisDelim_ == oldChild)
        {
            setAxisDelim((TAxisDelim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
