/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AForExprsingle extends PExprsingle
{
    private PForexpr _forexpr_;

    public AForExprsingle()
    {
        // Constructor
    }

    public AForExprsingle(
        @SuppressWarnings("hiding") PForexpr _forexpr_)
    {
        // Constructor
        setForexpr(_forexpr_);

    }

    @Override
    public Object clone()
    {
        return new AForExprsingle(
            cloneNode(this._forexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForExprsingle(this);
    }

    public PForexpr getForexpr()
    {
        return this._forexpr_;
    }

    public void setForexpr(PForexpr node)
    {
        if(this._forexpr_ != null)
        {
            this._forexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forexpr_ == child)
        {
            this._forexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forexpr_ == oldChild)
        {
            setForexpr((PForexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
