/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AFunctioncall extends PFunctioncall
{
    private PQname _qname_;
    private TLparenth _lparenth_;
    private PFunctioncallPart _functioncallPart_;
    private TRparenth _rparenth_;

    public AFunctioncall()
    {
        // Constructor
    }

    public AFunctioncall(
        @SuppressWarnings("hiding") PQname _qname_,
        @SuppressWarnings("hiding") TLparenth _lparenth_,
        @SuppressWarnings("hiding") PFunctioncallPart _functioncallPart_,
        @SuppressWarnings("hiding") TRparenth _rparenth_)
    {
        // Constructor
        setQname(_qname_);

        setLparenth(_lparenth_);

        setFunctioncallPart(_functioncallPart_);

        setRparenth(_rparenth_);

    }

    @Override
    public Object clone()
    {
        return new AFunctioncall(
            cloneNode(this._qname_),
            cloneNode(this._lparenth_),
            cloneNode(this._functioncallPart_),
            cloneNode(this._rparenth_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctioncall(this);
    }

    public PQname getQname()
    {
        return this._qname_;
    }

    public void setQname(PQname node)
    {
        if(this._qname_ != null)
        {
            this._qname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qname_ = node;
    }

    public TLparenth getLparenth()
    {
        return this._lparenth_;
    }

    public void setLparenth(TLparenth node)
    {
        if(this._lparenth_ != null)
        {
            this._lparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lparenth_ = node;
    }

    public PFunctioncallPart getFunctioncallPart()
    {
        return this._functioncallPart_;
    }

    public void setFunctioncallPart(PFunctioncallPart node)
    {
        if(this._functioncallPart_ != null)
        {
            this._functioncallPart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functioncallPart_ = node;
    }

    public TRparenth getRparenth()
    {
        return this._rparenth_;
    }

    public void setRparenth(TRparenth node)
    {
        if(this._rparenth_ != null)
        {
            this._rparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rparenth_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._qname_)
            + toString(this._lparenth_)
            + toString(this._functioncallPart_)
            + toString(this._rparenth_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._qname_ == child)
        {
            this._qname_ = null;
            return;
        }

        if(this._lparenth_ == child)
        {
            this._lparenth_ = null;
            return;
        }

        if(this._functioncallPart_ == child)
        {
            this._functioncallPart_ = null;
            return;
        }

        if(this._rparenth_ == child)
        {
            this._rparenth_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._qname_ == oldChild)
        {
            setQname((PQname) newChild);
            return;
        }

        if(this._lparenth_ == oldChild)
        {
            setLparenth((TLparenth) newChild);
            return;
        }

        if(this._functioncallPart_ == oldChild)
        {
            setFunctioncallPart((PFunctioncallPart) newChild);
            return;
        }

        if(this._rparenth_ == oldChild)
        {
            setRparenth((TRparenth) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
