/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ALeGeneralcomp extends PGeneralcomp
{
    private TLeAbbrev _leAbbrev_;

    public ALeGeneralcomp()
    {
        // Constructor
    }

    public ALeGeneralcomp(
        @SuppressWarnings("hiding") TLeAbbrev _leAbbrev_)
    {
        // Constructor
        setLeAbbrev(_leAbbrev_);

    }

    @Override
    public Object clone()
    {
        return new ALeGeneralcomp(
            cloneNode(this._leAbbrev_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeGeneralcomp(this);
    }

    public TLeAbbrev getLeAbbrev()
    {
        return this._leAbbrev_;
    }

    public void setLeAbbrev(TLeAbbrev node)
    {
        if(this._leAbbrev_ != null)
        {
            this._leAbbrev_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leAbbrev_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leAbbrev_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leAbbrev_ == child)
        {
            this._leAbbrev_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leAbbrev_ == oldChild)
        {
            setLeAbbrev((TLeAbbrev) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
