/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ALetterNcnamestartchar extends PNcnamestartchar
{
    private TLetter _letter_;

    public ALetterNcnamestartchar()
    {
        // Constructor
    }

    public ALetterNcnamestartchar(
        @SuppressWarnings("hiding") TLetter _letter_)
    {
        // Constructor
        setLetter(_letter_);

    }

    @Override
    public Object clone()
    {
        return new ALetterNcnamestartchar(
            cloneNode(this._letter_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALetterNcnamestartchar(this);
    }

    public TLetter getLetter()
    {
        return this._letter_;
    }

    public void setLetter(TLetter node)
    {
        if(this._letter_ != null)
        {
            this._letter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._letter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._letter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._letter_ == child)
        {
            this._letter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._letter_ == oldChild)
        {
            setLetter((TLetter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
