/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AMinusAdditiveexprPartPart extends PAdditiveexprPartPart
{
    private TMinus2 _minus2_;

    public AMinusAdditiveexprPartPart()
    {
        // Constructor
    }

    public AMinusAdditiveexprPartPart(
        @SuppressWarnings("hiding") TMinus2 _minus2_)
    {
        // Constructor
        setMinus2(_minus2_);

    }

    @Override
    public Object clone()
    {
        return new AMinusAdditiveexprPartPart(
            cloneNode(this._minus2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAdditiveexprPartPart(this);
    }

    public TMinus2 getMinus2()
    {
        return this._minus2_;
    }

    public void setMinus2(TMinus2 node)
    {
        if(this._minus2_ != null)
        {
            this._minus2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus2_ == child)
        {
            this._minus2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus2_ == oldChild)
        {
            setMinus2((TMinus2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
