/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ANcomppreNodecomp extends PNodecomp
{
    private TNcompPrecedes _ncompPrecedes_;

    public ANcomppreNodecomp()
    {
        // Constructor
    }

    public ANcomppreNodecomp(
        @SuppressWarnings("hiding") TNcompPrecedes _ncompPrecedes_)
    {
        // Constructor
        setNcompPrecedes(_ncompPrecedes_);

    }

    @Override
    public Object clone()
    {
        return new ANcomppreNodecomp(
            cloneNode(this._ncompPrecedes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANcomppreNodecomp(this);
    }

    public TNcompPrecedes getNcompPrecedes()
    {
        return this._ncompPrecedes_;
    }

    public void setNcompPrecedes(TNcompPrecedes node)
    {
        if(this._ncompPrecedes_ != null)
        {
            this._ncompPrecedes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ncompPrecedes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ncompPrecedes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ncompPrecedes_ == child)
        {
            this._ncompPrecedes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ncompPrecedes_ == oldChild)
        {
            setNcompPrecedes((TNcompPrecedes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
