/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ANeValuecomp extends PValuecomp
{
    private TNe _ne_;

    public ANeValuecomp()
    {
        // Constructor
    }

    public ANeValuecomp(
        @SuppressWarnings("hiding") TNe _ne_)
    {
        // Constructor
        setNe(_ne_);

    }

    @Override
    public Object clone()
    {
        return new ANeValuecomp(
            cloneNode(this._ne_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeValuecomp(this);
    }

    public TNe getNe()
    {
        return this._ne_;
    }

    public void setNe(TNe node)
    {
        if(this._ne_ != null)
        {
            this._ne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ne_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ne_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ne_ == child)
        {
            this._ne_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ne_ == oldChild)
        {
            setNe((TNe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
