/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ANodeComparisonexprPartPart extends PComparisonexprPartPart
{
    private PNodecomp _nodecomp_;

    public ANodeComparisonexprPartPart()
    {
        // Constructor
    }

    public ANodeComparisonexprPartPart(
        @SuppressWarnings("hiding") PNodecomp _nodecomp_)
    {
        // Constructor
        setNodecomp(_nodecomp_);

    }

    @Override
    public Object clone()
    {
        return new ANodeComparisonexprPartPart(
            cloneNode(this._nodecomp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodeComparisonexprPartPart(this);
    }

    public PNodecomp getNodecomp()
    {
        return this._nodecomp_;
    }

    public void setNodecomp(PNodecomp node)
    {
        if(this._nodecomp_ != null)
        {
            this._nodecomp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nodecomp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nodecomp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nodecomp_ == child)
        {
            this._nodecomp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nodecomp_ == oldChild)
        {
            setNodecomp((PNodecomp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
