/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ANumericLiteral extends PLiteral
{
    private PNumericliteral _numericliteral_;

    public ANumericLiteral()
    {
        // Constructor
    }

    public ANumericLiteral(
        @SuppressWarnings("hiding") PNumericliteral _numericliteral_)
    {
        // Constructor
        setNumericliteral(_numericliteral_);

    }

    @Override
    public Object clone()
    {
        return new ANumericLiteral(
            cloneNode(this._numericliteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumericLiteral(this);
    }

    public PNumericliteral getNumericliteral()
    {
        return this._numericliteral_;
    }

    public void setNumericliteral(PNumericliteral node)
    {
        if(this._numericliteral_ != null)
        {
            this._numericliteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numericliteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numericliteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numericliteral_ == child)
        {
            this._numericliteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numericliteral_ == oldChild)
        {
            setNumericliteral((PNumericliteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
