/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class APath1Pathexpr extends PPathexpr
{
    private PPathexprPartOne _pathexprPartOne_;

    public APath1Pathexpr()
    {
        // Constructor
    }

    public APath1Pathexpr(
        @SuppressWarnings("hiding") PPathexprPartOne _pathexprPartOne_)
    {
        // Constructor
        setPathexprPartOne(_pathexprPartOne_);

    }

    @Override
    public Object clone()
    {
        return new APath1Pathexpr(
            cloneNode(this._pathexprPartOne_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPath1Pathexpr(this);
    }

    public PPathexprPartOne getPathexprPartOne()
    {
        return this._pathexprPartOne_;
    }

    public void setPathexprPartOne(PPathexprPartOne node)
    {
        if(this._pathexprPartOne_ != null)
        {
            this._pathexprPartOne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pathexprPartOne_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pathexprPartOne_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pathexprPartOne_ == child)
        {
            this._pathexprPartOne_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pathexprPartOne_ == oldChild)
        {
            setPathexprPartOne((PPathexprPartOne) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
