/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class APathexprPartOne extends PPathexprPartOne
{
    private TAbbrevRoot _abbrevRoot_;
    private PRelativepathexpr _relativepathexpr_;

    public APathexprPartOne()
    {
        // Constructor
    }

    public APathexprPartOne(
        @SuppressWarnings("hiding") TAbbrevRoot _abbrevRoot_,
        @SuppressWarnings("hiding") PRelativepathexpr _relativepathexpr_)
    {
        // Constructor
        setAbbrevRoot(_abbrevRoot_);

        setRelativepathexpr(_relativepathexpr_);

    }

    @Override
    public Object clone()
    {
        return new APathexprPartOne(
            cloneNode(this._abbrevRoot_),
            cloneNode(this._relativepathexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathexprPartOne(this);
    }

    public TAbbrevRoot getAbbrevRoot()
    {
        return this._abbrevRoot_;
    }

    public void setAbbrevRoot(TAbbrevRoot node)
    {
        if(this._abbrevRoot_ != null)
        {
            this._abbrevRoot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abbrevRoot_ = node;
    }

    public PRelativepathexpr getRelativepathexpr()
    {
        return this._relativepathexpr_;
    }

    public void setRelativepathexpr(PRelativepathexpr node)
    {
        if(this._relativepathexpr_ != null)
        {
            this._relativepathexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relativepathexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abbrevRoot_)
            + toString(this._relativepathexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abbrevRoot_ == child)
        {
            this._abbrevRoot_ = null;
            return;
        }

        if(this._relativepathexpr_ == child)
        {
            this._relativepathexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abbrevRoot_ == oldChild)
        {
            setAbbrevRoot((TAbbrevRoot) newChild);
            return;
        }

        if(this._relativepathexpr_ == oldChild)
        {
            setRelativepathexpr((PRelativepathexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
