/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class APathexprPartTwo extends PPathexprPartTwo
{
    private TAbbrevRootDesc _abbrevRootDesc_;
    private PRelativepathexpr _relativepathexpr_;

    public APathexprPartTwo()
    {
        // Constructor
    }

    public APathexprPartTwo(
        @SuppressWarnings("hiding") TAbbrevRootDesc _abbrevRootDesc_,
        @SuppressWarnings("hiding") PRelativepathexpr _relativepathexpr_)
    {
        // Constructor
        setAbbrevRootDesc(_abbrevRootDesc_);

        setRelativepathexpr(_relativepathexpr_);

    }

    @Override
    public Object clone()
    {
        return new APathexprPartTwo(
            cloneNode(this._abbrevRootDesc_),
            cloneNode(this._relativepathexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathexprPartTwo(this);
    }

    public TAbbrevRootDesc getAbbrevRootDesc()
    {
        return this._abbrevRootDesc_;
    }

    public void setAbbrevRootDesc(TAbbrevRootDesc node)
    {
        if(this._abbrevRootDesc_ != null)
        {
            this._abbrevRootDesc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abbrevRootDesc_ = node;
    }

    public PRelativepathexpr getRelativepathexpr()
    {
        return this._relativepathexpr_;
    }

    public void setRelativepathexpr(PRelativepathexpr node)
    {
        if(this._relativepathexpr_ != null)
        {
            this._relativepathexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relativepathexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abbrevRootDesc_)
            + toString(this._relativepathexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abbrevRootDesc_ == child)
        {
            this._abbrevRootDesc_ = null;
            return;
        }

        if(this._relativepathexpr_ == child)
        {
            this._relativepathexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abbrevRootDesc_ == oldChild)
        {
            setAbbrevRootDesc((TAbbrevRootDesc) newChild);
            return;
        }

        if(this._relativepathexpr_ == oldChild)
        {
            setRelativepathexpr((PRelativepathexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
