/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class APiKindtest extends PKindtest
{
    private PPitest _pitest_;

    public APiKindtest()
    {
        // Constructor
    }

    public APiKindtest(
        @SuppressWarnings("hiding") PPitest _pitest_)
    {
        // Constructor
        setPitest(_pitest_);

    }

    @Override
    public Object clone()
    {
        return new APiKindtest(
            cloneNode(this._pitest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPiKindtest(this);
    }

    public PPitest getPitest()
    {
        return this._pitest_;
    }

    public void setPitest(PPitest node)
    {
        if(this._pitest_ != null)
        {
            this._pitest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pitest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pitest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pitest_ == child)
        {
            this._pitest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pitest_ == oldChild)
        {
            setPitest((PPitest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
