/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AQuantifExprsingle extends PExprsingle
{
    private PQuantifiedexpr _quantifiedexpr_;

    public AQuantifExprsingle()
    {
        // Constructor
    }

    public AQuantifExprsingle(
        @SuppressWarnings("hiding") PQuantifiedexpr _quantifiedexpr_)
    {
        // Constructor
        setQuantifiedexpr(_quantifiedexpr_);

    }

    @Override
    public Object clone()
    {
        return new AQuantifExprsingle(
            cloneNode(this._quantifiedexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQuantifExprsingle(this);
    }

    public PQuantifiedexpr getQuantifiedexpr()
    {
        return this._quantifiedexpr_;
    }

    public void setQuantifiedexpr(PQuantifiedexpr node)
    {
        if(this._quantifiedexpr_ != null)
        {
            this._quantifiedexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._quantifiedexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._quantifiedexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._quantifiedexpr_ == child)
        {
            this._quantifiedexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._quantifiedexpr_ == oldChild)
        {
            setQuantifiedexpr((PQuantifiedexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
