/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AReverseaxisPartFour extends PReverseaxisPartFour
{
    private TAxisPreceding _axisPreceding_;
    private TAxisDelim _axisDelim_;

    public AReverseaxisPartFour()
    {
        // Constructor
    }

    public AReverseaxisPartFour(
        @SuppressWarnings("hiding") TAxisPreceding _axisPreceding_,
        @SuppressWarnings("hiding") TAxisDelim _axisDelim_)
    {
        // Constructor
        setAxisPreceding(_axisPreceding_);

        setAxisDelim(_axisDelim_);

    }

    @Override
    public Object clone()
    {
        return new AReverseaxisPartFour(
            cloneNode(this._axisPreceding_),
            cloneNode(this._axisDelim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReverseaxisPartFour(this);
    }

    public TAxisPreceding getAxisPreceding()
    {
        return this._axisPreceding_;
    }

    public void setAxisPreceding(TAxisPreceding node)
    {
        if(this._axisPreceding_ != null)
        {
            this._axisPreceding_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisPreceding_ = node;
    }

    public TAxisDelim getAxisDelim()
    {
        return this._axisDelim_;
    }

    public void setAxisDelim(TAxisDelim node)
    {
        if(this._axisDelim_ != null)
        {
            this._axisDelim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisDelim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._axisPreceding_)
            + toString(this._axisDelim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._axisPreceding_ == child)
        {
            this._axisPreceding_ = null;
            return;
        }

        if(this._axisDelim_ == child)
        {
            this._axisDelim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._axisPreceding_ == oldChild)
        {
            setAxisPreceding((TAxisPreceding) newChild);
            return;
        }

        if(this._axisDelim_ == oldChild)
        {
            setAxisDelim((TAxisDelim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
