/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AReverseaxisPartOne extends PReverseaxisPartOne
{
    private TAxisParent _axisParent_;
    private TAxisDelim _axisDelim_;

    public AReverseaxisPartOne()
    {
        // Constructor
    }

    public AReverseaxisPartOne(
        @SuppressWarnings("hiding") TAxisParent _axisParent_,
        @SuppressWarnings("hiding") TAxisDelim _axisDelim_)
    {
        // Constructor
        setAxisParent(_axisParent_);

        setAxisDelim(_axisDelim_);

    }

    @Override
    public Object clone()
    {
        return new AReverseaxisPartOne(
            cloneNode(this._axisParent_),
            cloneNode(this._axisDelim_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReverseaxisPartOne(this);
    }

    public TAxisParent getAxisParent()
    {
        return this._axisParent_;
    }

    public void setAxisParent(TAxisParent node)
    {
        if(this._axisParent_ != null)
        {
            this._axisParent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisParent_ = node;
    }

    public TAxisDelim getAxisDelim()
    {
        return this._axisDelim_;
    }

    public void setAxisDelim(TAxisDelim node)
    {
        if(this._axisDelim_ != null)
        {
            this._axisDelim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._axisDelim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._axisParent_)
            + toString(this._axisDelim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._axisParent_ == child)
        {
            this._axisParent_ = null;
            return;
        }

        if(this._axisDelim_ == child)
        {
            this._axisDelim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._axisParent_ == oldChild)
        {
            setAxisParent((TAxisParent) newChild);
            return;
        }

        if(this._axisDelim_ == oldChild)
        {
            setAxisDelim((TAxisDelim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
