/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AReverse4Reverseaxis extends PReverseaxis
{
    private PReverseaxisPartFour _reverseaxisPartFour_;

    public AReverse4Reverseaxis()
    {
        // Constructor
    }

    public AReverse4Reverseaxis(
        @SuppressWarnings("hiding") PReverseaxisPartFour _reverseaxisPartFour_)
    {
        // Constructor
        setReverseaxisPartFour(_reverseaxisPartFour_);

    }

    @Override
    public Object clone()
    {
        return new AReverse4Reverseaxis(
            cloneNode(this._reverseaxisPartFour_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReverse4Reverseaxis(this);
    }

    public PReverseaxisPartFour getReverseaxisPartFour()
    {
        return this._reverseaxisPartFour_;
    }

    public void setReverseaxisPartFour(PReverseaxisPartFour node)
    {
        if(this._reverseaxisPartFour_ != null)
        {
            this._reverseaxisPartFour_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reverseaxisPartFour_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reverseaxisPartFour_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reverseaxisPartFour_ == child)
        {
            this._reverseaxisPartFour_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reverseaxisPartFour_ == oldChild)
        {
            setReverseaxisPartFour((PReverseaxisPartFour) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
