/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ARootRelativepathexprPartPart extends PRelativepathexprPartPart
{
    private TAbbrevRoot _abbrevRoot_;

    public ARootRelativepathexprPartPart()
    {
        // Constructor
    }

    public ARootRelativepathexprPartPart(
        @SuppressWarnings("hiding") TAbbrevRoot _abbrevRoot_)
    {
        // Constructor
        setAbbrevRoot(_abbrevRoot_);

    }

    @Override
    public Object clone()
    {
        return new ARootRelativepathexprPartPart(
            cloneNode(this._abbrevRoot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARootRelativepathexprPartPart(this);
    }

    public TAbbrevRoot getAbbrevRoot()
    {
        return this._abbrevRoot_;
    }

    public void setAbbrevRoot(TAbbrevRoot node)
    {
        if(this._abbrevRoot_ != null)
        {
            this._abbrevRoot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abbrevRoot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abbrevRoot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abbrevRoot_ == child)
        {
            this._abbrevRoot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abbrevRoot_ == oldChild)
        {
            setAbbrevRoot((TAbbrevRoot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
