/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ASequencetypePartOne extends PSequencetypePartOne
{
    private TFnEmptySequence _fnEmptySequence_;
    private TLparenth _lparenth_;
    private TRparenth _rparenth_;

    public ASequencetypePartOne()
    {
        // Constructor
    }

    public ASequencetypePartOne(
        @SuppressWarnings("hiding") TFnEmptySequence _fnEmptySequence_,
        @SuppressWarnings("hiding") TLparenth _lparenth_,
        @SuppressWarnings("hiding") TRparenth _rparenth_)
    {
        // Constructor
        setFnEmptySequence(_fnEmptySequence_);

        setLparenth(_lparenth_);

        setRparenth(_rparenth_);

    }

    @Override
    public Object clone()
    {
        return new ASequencetypePartOne(
            cloneNode(this._fnEmptySequence_),
            cloneNode(this._lparenth_),
            cloneNode(this._rparenth_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequencetypePartOne(this);
    }

    public TFnEmptySequence getFnEmptySequence()
    {
        return this._fnEmptySequence_;
    }

    public void setFnEmptySequence(TFnEmptySequence node)
    {
        if(this._fnEmptySequence_ != null)
        {
            this._fnEmptySequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fnEmptySequence_ = node;
    }

    public TLparenth getLparenth()
    {
        return this._lparenth_;
    }

    public void setLparenth(TLparenth node)
    {
        if(this._lparenth_ != null)
        {
            this._lparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lparenth_ = node;
    }

    public TRparenth getRparenth()
    {
        return this._rparenth_;
    }

    public void setRparenth(TRparenth node)
    {
        if(this._rparenth_ != null)
        {
            this._rparenth_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rparenth_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fnEmptySequence_)
            + toString(this._lparenth_)
            + toString(this._rparenth_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fnEmptySequence_ == child)
        {
            this._fnEmptySequence_ = null;
            return;
        }

        if(this._lparenth_ == child)
        {
            this._lparenth_ = null;
            return;
        }

        if(this._rparenth_ == child)
        {
            this._rparenth_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fnEmptySequence_ == oldChild)
        {
            setFnEmptySequence((TFnEmptySequence) newChild);
            return;
        }

        if(this._lparenth_ == oldChild)
        {
            setLparenth((TLparenth) newChild);
            return;
        }

        if(this._rparenth_ == oldChild)
        {
            setRparenth((TRparenth) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
