/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleforclausePart extends PSimpleforclausePart
{
    private TComma _comma_;
    private TDollar _dollar_;
    private PVarname _varname_;
    private TKeywordIn _keywordIn_;
    private PExprsingle _exprsingle_;

    public ASimpleforclausePart()
    {
        // Constructor
    }

    public ASimpleforclausePart(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") TDollar _dollar_,
        @SuppressWarnings("hiding") PVarname _varname_,
        @SuppressWarnings("hiding") TKeywordIn _keywordIn_,
        @SuppressWarnings("hiding") PExprsingle _exprsingle_)
    {
        // Constructor
        setComma(_comma_);

        setDollar(_dollar_);

        setVarname(_varname_);

        setKeywordIn(_keywordIn_);

        setExprsingle(_exprsingle_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleforclausePart(
            cloneNode(this._comma_),
            cloneNode(this._dollar_),
            cloneNode(this._varname_),
            cloneNode(this._keywordIn_),
            cloneNode(this._exprsingle_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleforclausePart(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public TDollar getDollar()
    {
        return this._dollar_;
    }

    public void setDollar(TDollar node)
    {
        if(this._dollar_ != null)
        {
            this._dollar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dollar_ = node;
    }

    public PVarname getVarname()
    {
        return this._varname_;
    }

    public void setVarname(PVarname node)
    {
        if(this._varname_ != null)
        {
            this._varname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varname_ = node;
    }

    public TKeywordIn getKeywordIn()
    {
        return this._keywordIn_;
    }

    public void setKeywordIn(TKeywordIn node)
    {
        if(this._keywordIn_ != null)
        {
            this._keywordIn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordIn_ = node;
    }

    public PExprsingle getExprsingle()
    {
        return this._exprsingle_;
    }

    public void setExprsingle(PExprsingle node)
    {
        if(this._exprsingle_ != null)
        {
            this._exprsingle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprsingle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._dollar_)
            + toString(this._varname_)
            + toString(this._keywordIn_)
            + toString(this._exprsingle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._dollar_ == child)
        {
            this._dollar_ = null;
            return;
        }

        if(this._varname_ == child)
        {
            this._varname_ = null;
            return;
        }

        if(this._keywordIn_ == child)
        {
            this._keywordIn_ = null;
            return;
        }

        if(this._exprsingle_ == child)
        {
            this._exprsingle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._dollar_ == oldChild)
        {
            setDollar((TDollar) newChild);
            return;
        }

        if(this._varname_ == oldChild)
        {
            setVarname((PVarname) newChild);
            return;
        }

        if(this._keywordIn_ == oldChild)
        {
            setKeywordIn((TKeywordIn) newChild);
            return;
        }

        if(this._exprsingle_ == oldChild)
        {
            setExprsingle((PExprsingle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
