/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class ASomeSomeEveryPart extends PSomeEveryPart
{
    private TKeywordSome _keywordSome_;

    public ASomeSomeEveryPart()
    {
        // Constructor
    }

    public ASomeSomeEveryPart(
        @SuppressWarnings("hiding") TKeywordSome _keywordSome_)
    {
        // Constructor
        setKeywordSome(_keywordSome_);

    }

    @Override
    public Object clone()
    {
        return new ASomeSomeEveryPart(
            cloneNode(this._keywordSome_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomeSomeEveryPart(this);
    }

    public TKeywordSome getKeywordSome()
    {
        return this._keywordSome_;
    }

    public void setKeywordSome(TKeywordSome node)
    {
        if(this._keywordSome_ != null)
        {
            this._keywordSome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordSome_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordSome_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordSome_ == child)
        {
            this._keywordSome_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordSome_ == oldChild)
        {
            setKeywordSome((TKeywordSome) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
