/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AStarMultiplicativeexprPartPart extends PMultiplicativeexprPartPart
{
    private TStar2 _star2_;

    public AStarMultiplicativeexprPartPart()
    {
        // Constructor
    }

    public AStarMultiplicativeexprPartPart(
        @SuppressWarnings("hiding") TStar2 _star2_)
    {
        // Constructor
        setStar2(_star2_);

    }

    @Override
    public Object clone()
    {
        return new AStarMultiplicativeexprPartPart(
            cloneNode(this._star2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStarMultiplicativeexprPartPart(this);
    }

    public TStar2 getStar2()
    {
        return this._star2_;
    }

    public void setStar2(TStar2 node)
    {
        if(this._star2_ != null)
        {
            this._star2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._star2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._star2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._star2_ == child)
        {
            this._star2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._star2_ == oldChild)
        {
            setStar2((TStar2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
