/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AUnionkeyUnionexprPartPart extends PUnionexprPartPart
{
    private TKeywordUnion _keywordUnion_;

    public AUnionkeyUnionexprPartPart()
    {
        // Constructor
    }

    public AUnionkeyUnionexprPartPart(
        @SuppressWarnings("hiding") TKeywordUnion _keywordUnion_)
    {
        // Constructor
        setKeywordUnion(_keywordUnion_);

    }

    @Override
    public Object clone()
    {
        return new AUnionkeyUnionexprPartPart(
            cloneNode(this._keywordUnion_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnionkeyUnionexprPartPart(this);
    }

    public TKeywordUnion getKeywordUnion()
    {
        return this._keywordUnion_;
    }

    public void setKeywordUnion(TKeywordUnion node)
    {
        if(this._keywordUnion_ != null)
        {
            this._keywordUnion_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordUnion_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordUnion_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordUnion_ == child)
        {
            this._keywordUnion_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordUnion_ == oldChild)
        {
            setKeywordUnion((TKeywordUnion) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
