/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class AUnprefixedQname extends PQname
{
    private PUnprefixedname _unprefixedname_;

    public AUnprefixedQname()
    {
        // Constructor
    }

    public AUnprefixedQname(
        @SuppressWarnings("hiding") PUnprefixedname _unprefixedname_)
    {
        // Constructor
        setUnprefixedname(_unprefixedname_);

    }

    @Override
    public Object clone()
    {
        return new AUnprefixedQname(
            cloneNode(this._unprefixedname_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnprefixedQname(this);
    }

    public PUnprefixedname getUnprefixedname()
    {
        return this._unprefixedname_;
    }

    public void setUnprefixedname(PUnprefixedname node)
    {
        if(this._unprefixedname_ != null)
        {
            this._unprefixedname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unprefixedname_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unprefixedname_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unprefixedname_ == child)
        {
            this._unprefixedname_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unprefixedname_ == oldChild)
        {
            setUnprefixedname((PUnprefixedname) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
