/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TAbbrevAttrib extends Token
{
    public TAbbrevAttrib()
    {
        super.setText("@");
    }

    public TAbbrevAttrib(int line, int pos)
    {
        super.setText("@");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAbbrevAttrib(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAbbrevAttrib(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAbbrevAttrib text.");
    }
}
