/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TAxisPreceding extends Token
{
    public TAxisPreceding()
    {
        super.setText("preceding");
    }

    public TAxisPreceding(int line, int pos)
    {
        super.setText("preceding");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAxisPreceding(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAxisPreceding(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAxisPreceding text.");
    }
}
