/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TAxisAncestorOrSelf extends Token
{
    public TAxisAncestorOrSelf()
    {
        super.setText("ancestor-or-self");
    }

    public TAxisAncestorOrSelf(int line, int pos)
    {
        super.setText("ancestor-or-self");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAxisAncestorOrSelf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAxisAncestorOrSelf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAxisAncestorOrSelf text.");
    }
}
