/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TAxisPrecedingSibling extends Token
{
    public TAxisPrecedingSibling()
    {
        super.setText("preceding-sibling");
    }

    public TAxisPrecedingSibling(int line, int pos)
    {
        super.setText("preceding-sibling");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAxisPrecedingSibling(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAxisPrecedingSibling(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAxisPrecedingSibling text.");
    }
}
