/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TAxisFollowing extends Token
{
    public TAxisFollowing()
    {
        super.setText("following");
    }

    public TAxisFollowing(int line, int pos)
    {
        super.setText("following");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAxisFollowing(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAxisFollowing(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAxisFollowing text.");
    }
}
