/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TFnComment extends Token
{
    public TFnComment()
    {
        super.setText("comment");
    }

    public TFnComment(int line, int pos)
    {
        super.setText("comment");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFnComment(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFnComment(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFnComment text.");
    }
}
