/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TFnItem extends Token
{
    public TFnItem()
    {
        super.setText("item");
    }

    public TFnItem(int line, int pos)
    {
        super.setText("item");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFnItem(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFnItem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFnItem text.");
    }
}
