/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TFnNode extends Token
{
    public TFnNode()
    {
        super.setText("node");
    }

    public TFnNode(int line, int pos)
    {
        super.setText("node");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFnNode(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFnNode(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFnNode text.");
    }
}
