/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TFnProcessingInstruction extends Token
{
    public TFnProcessingInstruction()
    {
        super.setText("processing-instruction");
    }

    public TFnProcessingInstruction(int line, int pos)
    {
        super.setText("processing-instruction");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFnProcessingInstruction(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFnProcessingInstruction(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFnProcessingInstruction text.");
    }
}
