/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TFnSchemaAttribute extends Token
{
    public TFnSchemaAttribute()
    {
        super.setText("schema-attribute");
    }

    public TFnSchemaAttribute(int line, int pos)
    {
        super.setText("schema-attribute");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFnSchemaAttribute(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFnSchemaAttribute(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFnSchemaAttribute text.");
    }
}
