/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TGe extends Token
{
    public TGe()
    {
        super.setText("ge");
    }

    public TGe(int line, int pos)
    {
        super.setText("ge");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGe(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGe text.");
    }
}
