/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TLe extends Token
{
    public TLe()
    {
        super.setText("le");
    }

    public TLe(int line, int pos)
    {
        super.setText("le");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLe(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLe text.");
    }
}
