/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.interrupt.cc.xpath.node;

import com.interrupt.cc.xpath.analysis.*;

@SuppressWarnings("nls")
public final class TXmlns extends Token
{
    public TXmlns()
    {
        super.setText("xmlns");
    }

    public TXmlns(int line, int pos)
    {
        super.setText("xmlns");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TXmlns(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXmlns(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TXmlns text.");
    }
}
