/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import java.util.*;
import nisse.analysis.*;

@SuppressWarnings("nls")
public final class ABeblock extends PBeblock
{
    private TLcurly _lcurly_;
    private final LinkedList<TSpace> _first_ = new LinkedList<TSpace>();
    private TChar _char_;
    private final LinkedList<TSpace> _second_ = new LinkedList<TSpace>();
    private PBeblockv1 _beblockv1_;
    private TRcurly _rcurly_;

    public ABeblock()
    {
        // Constructor
    }

    public ABeblock(
        @SuppressWarnings("hiding") TLcurly _lcurly_,
        @SuppressWarnings("hiding") List<TSpace> _first_,
        @SuppressWarnings("hiding") TChar _char_,
        @SuppressWarnings("hiding") List<TSpace> _second_,
        @SuppressWarnings("hiding") PBeblockv1 _beblockv1_,
        @SuppressWarnings("hiding") TRcurly _rcurly_)
    {
        // Constructor
        setLcurly(_lcurly_);

        setFirst(_first_);

        setChar(_char_);

        setSecond(_second_);

        setBeblockv1(_beblockv1_);

        setRcurly(_rcurly_);

    }

    @Override
    public Object clone()
    {
        return new ABeblock(
            cloneNode(this._lcurly_),
            cloneList(this._first_),
            cloneNode(this._char_),
            cloneList(this._second_),
            cloneNode(this._beblockv1_),
            cloneNode(this._rcurly_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABeblock(this);
    }

    public TLcurly getLcurly()
    {
        return this._lcurly_;
    }

    public void setLcurly(TLcurly node)
    {
        if(this._lcurly_ != null)
        {
            this._lcurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lcurly_ = node;
    }

    public LinkedList<TSpace> getFirst()
    {
        return this._first_;
    }

    public void setFirst(List<TSpace> list)
    {
        this._first_.clear();
        this._first_.addAll(list);
        for(TSpace e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TChar getChar()
    {
        return this._char_;
    }

    public void setChar(TChar node)
    {
        if(this._char_ != null)
        {
            this._char_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._char_ = node;
    }

    public LinkedList<TSpace> getSecond()
    {
        return this._second_;
    }

    public void setSecond(List<TSpace> list)
    {
        this._second_.clear();
        this._second_.addAll(list);
        for(TSpace e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PBeblockv1 getBeblockv1()
    {
        return this._beblockv1_;
    }

    public void setBeblockv1(PBeblockv1 node)
    {
        if(this._beblockv1_ != null)
        {
            this._beblockv1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._beblockv1_ = node;
    }

    public TRcurly getRcurly()
    {
        return this._rcurly_;
    }

    public void setRcurly(TRcurly node)
    {
        if(this._rcurly_ != null)
        {
            this._rcurly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rcurly_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lcurly_)
            + toString(this._first_)
            + toString(this._char_)
            + toString(this._second_)
            + toString(this._beblockv1_)
            + toString(this._rcurly_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lcurly_ == child)
        {
            this._lcurly_ = null;
            return;
        }

        if(this._first_.remove(child))
        {
            return;
        }

        if(this._char_ == child)
        {
            this._char_ = null;
            return;
        }

        if(this._second_.remove(child))
        {
            return;
        }

        if(this._beblockv1_ == child)
        {
            this._beblockv1_ = null;
            return;
        }

        if(this._rcurly_ == child)
        {
            this._rcurly_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lcurly_ == oldChild)
        {
            setLcurly((TLcurly) newChild);
            return;
        }

        for(ListIterator<TSpace> i = this._first_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TSpace) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._char_ == oldChild)
        {
            setChar((TChar) newChild);
            return;
        }

        for(ListIterator<TSpace> i = this._second_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TSpace) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._beblockv1_ == oldChild)
        {
            setBeblockv1((PBeblockv1) newChild);
            return;
        }

        if(this._rcurly_ == oldChild)
        {
            setRcurly((TRcurly) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
