/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class AItemlistItemlistv1 extends PItemlistv1
{
    private PItemlist _itemlist_;

    public AItemlistItemlistv1()
    {
        // Constructor
    }

    public AItemlistItemlistv1(
        @SuppressWarnings("hiding") PItemlist _itemlist_)
    {
        // Constructor
        setItemlist(_itemlist_);

    }

    @Override
    public Object clone()
    {
        return new AItemlistItemlistv1(
            cloneNode(this._itemlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAItemlistItemlistv1(this);
    }

    public PItemlist getItemlist()
    {
        return this._itemlist_;
    }

    public void setItemlist(PItemlist node)
    {
        if(this._itemlist_ != null)
        {
            this._itemlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._itemlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._itemlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._itemlist_ == child)
        {
            this._itemlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._itemlist_ == oldChild)
        {
            setItemlist((PItemlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
