/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class ASpaceCharall extends PCharall
{
    private TSpace _space_;

    public ASpaceCharall()
    {
        // Constructor
    }

    public ASpaceCharall(
        @SuppressWarnings("hiding") TSpace _space_)
    {
        // Constructor
        setSpace(_space_);

    }

    @Override
    public Object clone()
    {
        return new ASpaceCharall(
            cloneNode(this._space_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpaceCharall(this);
    }

    public TSpace getSpace()
    {
        return this._space_;
    }

    public void setSpace(TSpace node)
    {
        if(this._space_ != null)
        {
            this._space_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._space_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._space_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._space_ == child)
        {
            this._space_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._space_ == oldChild)
        {
            setSpace((TSpace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
