/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class AUnderscoreKwdv1 extends PKwdv1
{
    private TUnderscore _underscore_;

    public AUnderscoreKwdv1()
    {
        // Constructor
    }

    public AUnderscoreKwdv1(
        @SuppressWarnings("hiding") TUnderscore _underscore_)
    {
        // Constructor
        setUnderscore(_underscore_);

    }

    @Override
    public Object clone()
    {
        return new AUnderscoreKwdv1(
            cloneNode(this._underscore_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnderscoreKwdv1(this);
    }

    public TUnderscore getUnderscore()
    {
        return this._underscore_;
    }

    public void setUnderscore(TUnderscore node)
    {
        if(this._underscore_ != null)
        {
            this._underscore_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._underscore_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._underscore_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._underscore_ == child)
        {
            this._underscore_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._underscore_ == oldChild)
        {
            setUnderscore((TUnderscore) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
