/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.node;

import nisse.analysis.*;

@SuppressWarnings("nls")
public final class TEndkwd extends Token
{
    public TEndkwd()
    {
        super.setText("@end");
    }

    public TEndkwd(int line, int pos)
    {
        super.setText("@end");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndkwd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndkwd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndkwd text.");
    }
}
