/* This file was generated by SableCC (http://www.sablecc.org/). */

package nisse.parser;

import nisse.lexer.*;
import nisse.node.*;
import nisse.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAnisse1Nisse */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAnisse2Nisse */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAblockblocks1Blocks */
		    {
			ArrayList list = new2();
			push(goTo(1), list, false);
		    }
		    break;
                    case 3: /* reduce AAblockblocks2Blocks */
		    {
			ArrayList list = new3();
			push(goTo(1), list, false);
		    }
		    break;
                    case 4: /* reduce ASettingBlocks */
		    {
			ArrayList list = new4();
			push(goTo(1), list, false);
		    }
		    break;
                    case 5: /* reduce ASettingLines */
		    {
			ArrayList list = new5();
			push(goTo(2), list, false);
		    }
		    break;
                    case 6: /* reduce ANumerationLines */
		    {
			ArrayList list = new6();
			push(goTo(2), list, false);
		    }
		    break;
                    case 7: /* reduce AItemlistLines */
		    {
			ArrayList list = new7();
			push(goTo(2), list, false);
		    }
		    break;
                    case 8: /* reduce APlaintextLines */
		    {
			ArrayList list = new8();
			push(goTo(2), list, false);
		    }
		    break;
                    case 9: /* reduce ANumeration */
		    {
			ArrayList list = new9();
			push(goTo(3), list, false);
		    }
		    break;
                    case 10: /* reduce APlaintextNumerationv1 */
		    {
			ArrayList list = new10();
			push(goTo(4), list, false);
		    }
		    break;
                    case 11: /* reduce ANumerationNumerationv1 */
		    {
			ArrayList list = new11();
			push(goTo(4), list, false);
		    }
		    break;
                    case 12: /* reduce AItemlist */
		    {
			ArrayList list = new12();
			push(goTo(5), list, false);
		    }
		    break;
                    case 13: /* reduce APlaintextItemlistv1 */
		    {
			ArrayList list = new13();
			push(goTo(6), list, false);
		    }
		    break;
                    case 14: /* reduce AItemlistItemlistv1 */
		    {
			ArrayList list = new14();
			push(goTo(6), list, false);
		    }
		    break;
                    case 15: /* reduce ABeginblock */
		    {
			ArrayList list = new15();
			push(goTo(7), list, false);
		    }
		    break;
                    case 16: /* reduce AEndblock */
		    {
			ArrayList list = new16();
			push(goTo(8), list, false);
		    }
		    break;
                    case 17: /* reduce AAbeblock1Beblock */
		    {
			ArrayList list = new17();
			push(goTo(9), list, false);
		    }
		    break;
                    case 18: /* reduce AAbeblock2Beblock */
		    {
			ArrayList list = new18();
			push(goTo(9), list, false);
		    }
		    break;
                    case 19: /* reduce ABeblockv1 */
		    {
			ArrayList list = new19();
			push(goTo(10), list, false);
		    }
		    break;
                    case 20: /* reduce ASettingblock */
		    {
			ArrayList list = new20();
			push(goTo(11), list, false);
		    }
		    break;
                    case 21: /* reduce APlains */
		    {
			ArrayList list = new21();
			push(goTo(12), list, false);
		    }
		    break;
                    case 22: /* reduce AShortblockPlainsv1 */
		    {
			ArrayList list = new22();
			push(goTo(13), list, false);
		    }
		    break;
                    case 23: /* reduce ACharallPlainsv1 */
		    {
			ArrayList list = new23();
			push(goTo(13), list, false);
		    }
		    break;
                    case 24: /* reduce AAshortblock1Shortblock */
		    {
			ArrayList list = new24();
			push(goTo(14), list, false);
		    }
		    break;
                    case 25: /* reduce AAshortblock2Shortblock */
		    {
			ArrayList list = new25();
			push(goTo(14), list, false);
		    }
		    break;
                    case 26: /* reduce AShortidents */
		    {
			ArrayList list = new26();
			push(goTo(15), list, false);
		    }
		    break;
                    case 27: /* reduce AShortident */
		    {
			ArrayList list = new27();
			push(goTo(16), list, false);
		    }
		    break;
                    case 28: /* reduce ACharShortidentv1 */
		    {
			ArrayList list = new28();
			push(goTo(17), list, false);
		    }
		    break;
                    case 29: /* reduce ADigitShortidentv1 */
		    {
			ArrayList list = new29();
			push(goTo(17), list, false);
		    }
		    break;
                    case 30: /* reduce AKwd */
		    {
			ArrayList list = new30();
			push(goTo(18), list, false);
		    }
		    break;
                    case 31: /* reduce AColonCharall */
		    {
			ArrayList list = new31();
			push(goTo(19), list, false);
		    }
		    break;
                    case 32: /* reduce ADigitCharall */
		    {
			ArrayList list = new32();
			push(goTo(19), list, false);
		    }
		    break;
                    case 33: /* reduce ASemicolonCharall */
		    {
			ArrayList list = new33();
			push(goTo(19), list, false);
		    }
		    break;
                    case 34: /* reduce APercentCharall */
		    {
			ArrayList list = new34();
			push(goTo(19), list, false);
		    }
		    break;
                    case 35: /* reduce AForwardslashCharall */
		    {
			ArrayList list = new35();
			push(goTo(19), list, false);
		    }
		    break;
                    case 36: /* reduce ABackslashCharall */
		    {
			ArrayList list = new36();
			push(goTo(19), list, false);
		    }
		    break;
                    case 37: /* reduce AMorecharCharall */
		    {
			ArrayList list = new37();
			push(goTo(19), list, false);
		    }
		    break;
                    case 38: /* reduce ACharCharall */
		    {
			ArrayList list = new38();
			push(goTo(19), list, false);
		    }
		    break;
                    case 39: /* reduce ATerminal$Blocks */
		    {
			ArrayList list = new39();
			push(goTo(20), list, true);
		    }
		    break;
                    case 40: /* reduce ANonTerminal$Blocks */
		    {
			ArrayList list = new40();
			push(goTo(20), list, true);
		    }
		    break;
                    case 41: /* reduce ATerminal$Lines */
		    {
			ArrayList list = new41();
			push(goTo(21), list, true);
		    }
		    break;
                    case 42: /* reduce ANonTerminal$Lines */
		    {
			ArrayList list = new42();
			push(goTo(21), list, true);
		    }
		    break;
                    case 43: /* reduce ATerminal$Eol */
		    {
			ArrayList list = new43();
			push(goTo(22), list, true);
		    }
		    break;
                    case 44: /* reduce ANonTerminal$Eol */
		    {
			ArrayList list = new44();
			push(goTo(22), list, true);
		    }
		    break;
                    case 45: /* reduce ATerminal$Plainsv1 */
		    {
			ArrayList list = new45();
			push(goTo(23), list, true);
		    }
		    break;
                    case 46: /* reduce ANonTerminal$Plainsv1 */
		    {
			ArrayList list = new46();
			push(goTo(23), list, true);
		    }
		    break;
                    case 47: /* reduce ATerminal$Shortident */
		    {
			ArrayList list = new47();
			push(goTo(24), list, true);
		    }
		    break;
                    case 48: /* reduce ANonTerminal$Shortident */
		    {
			ArrayList list = new48();
			push(goTo(24), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PNisse node1 = (PNisse) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AAnisse1Nisse */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PNisse pnisseNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        }

        pnisseNode1 = new ANisse(listNode2);
        }
	nodeList.add(pnisseNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAnisse2Nisse */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PNisse pnisseNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pnisseNode1 = new ANisse(listNode3);
        }
	nodeList.add(pnisseNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AAblockblocks1Blocks */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBlocks pblocksNode1;
        {
            // Block
        PBeginblock pbeginblockNode2;
        LinkedList listNode3 = new LinkedList();
        PEndblock pendblockNode4;
        pbeginblockNode2 = (PBeginblock)nodeArrayList1.get(0);
        {
            // Block
        }
        pendblockNode4 = (PEndblock)nodeArrayList2.get(0);

        pblocksNode1 = new ABlockBlocks(pbeginblockNode2, listNode3, pendblockNode4);
        }
	nodeList.add(pblocksNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AAblockblocks2Blocks */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBlocks pblocksNode1;
        {
            // Block
        PBeginblock pbeginblockNode2;
        LinkedList listNode4 = new LinkedList();
        PEndblock pendblockNode5;
        pbeginblockNode2 = (PBeginblock)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        pendblockNode5 = (PEndblock)nodeArrayList3.get(0);

        pblocksNode1 = new ABlockBlocks(pbeginblockNode2, listNode4, pendblockNode5);
        }
	nodeList.add(pblocksNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce ASettingBlocks */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBlocks pblocksNode1;
        {
            // Block
        PSettingblock psettingblockNode2;
        psettingblockNode2 = (PSettingblock)nodeArrayList1.get(0);

        pblocksNode1 = new ASettingBlocks(psettingblockNode2);
        }
	nodeList.add(pblocksNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ASettingLines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLines plinesNode1;
        {
            // Block
        PSettingblock psettingblockNode2;
        psettingblockNode2 = (PSettingblock)nodeArrayList1.get(0);

        plinesNode1 = new ASettingLines(psettingblockNode2);
        }
	nodeList.add(plinesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce ANumerationLines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLines plinesNode1;
        {
            // Block
        PNumeration pnumerationNode2;
        pnumerationNode2 = (PNumeration)nodeArrayList1.get(0);

        plinesNode1 = new ANumerationLines(pnumerationNode2);
        }
	nodeList.add(plinesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AItemlistLines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLines plinesNode1;
        {
            // Block
        PItemlist pitemlistNode2;
        pitemlistNode2 = (PItemlist)nodeArrayList1.get(0);

        plinesNode1 = new AItemlistLines(pitemlistNode2);
        }
	nodeList.add(plinesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce APlaintextLines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLines plinesNode1;
        {
            // Block
        PPlains pplainsNode2;
        TEol teolNode3;
        pplainsNode2 = (PPlains)nodeArrayList1.get(0);
        teolNode3 = (TEol)nodeArrayList2.get(0);

        plinesNode1 = new APlaintextLines(pplainsNode2, teolNode3);
        }
	nodeList.add(plinesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce ANumeration */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PNumeration pnumerationNode1;
        {
            // Block
        TNlist tnlistNode2;
        PNumerationv1 pnumerationv1Node3;
        tnlistNode2 = (TNlist)nodeArrayList1.get(0);
        pnumerationv1Node3 = (PNumerationv1)nodeArrayList2.get(0);

        pnumerationNode1 = new ANumeration(tnlistNode2, pnumerationv1Node3);
        }
	nodeList.add(pnumerationNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce APlaintextNumerationv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PNumerationv1 pnumerationv1Node1;
        {
            // Block
        PPlains pplainsNode2;
        TEol teolNode3;
        pplainsNode2 = (PPlains)nodeArrayList1.get(0);
        teolNode3 = (TEol)nodeArrayList2.get(0);

        pnumerationv1Node1 = new APlaintextNumerationv1(pplainsNode2, teolNode3);
        }
	nodeList.add(pnumerationv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce ANumerationNumerationv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PNumerationv1 pnumerationv1Node1;
        {
            // Block
        PNumeration pnumerationNode2;
        pnumerationNode2 = (PNumeration)nodeArrayList1.get(0);

        pnumerationv1Node1 = new ANumerationNumerationv1(pnumerationNode2);
        }
	nodeList.add(pnumerationv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AItemlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PItemlist pitemlistNode1;
        {
            // Block
        TBlist tblistNode2;
        PItemlistv1 pitemlistv1Node3;
        tblistNode2 = (TBlist)nodeArrayList1.get(0);
        pitemlistv1Node3 = (PItemlistv1)nodeArrayList2.get(0);

        pitemlistNode1 = new AItemlist(tblistNode2, pitemlistv1Node3);
        }
	nodeList.add(pitemlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce APlaintextItemlistv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PItemlistv1 pitemlistv1Node1;
        {
            // Block
        PPlains pplainsNode2;
        TEol teolNode3;
        pplainsNode2 = (PPlains)nodeArrayList1.get(0);
        teolNode3 = (TEol)nodeArrayList2.get(0);

        pitemlistv1Node1 = new APlaintextItemlistv1(pplainsNode2, teolNode3);
        }
	nodeList.add(pitemlistv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AItemlistItemlistv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PItemlistv1 pitemlistv1Node1;
        {
            // Block
        PItemlist pitemlistNode2;
        pitemlistNode2 = (PItemlist)nodeArrayList1.get(0);

        pitemlistv1Node1 = new AItemlistItemlistv1(pitemlistNode2);
        }
	nodeList.add(pitemlistv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce ABeginblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBeginblock pbeginblockNode1;
        {
            // Block
        TBeginkwd tbeginkwdNode2;
        PBeblock pbeblockNode3;
        TEol teolNode4;
        tbeginkwdNode2 = (TBeginkwd)nodeArrayList1.get(0);
        pbeblockNode3 = (PBeblock)nodeArrayList2.get(0);
        teolNode4 = (TEol)nodeArrayList3.get(0);

        pbeginblockNode1 = new ABeginblock(tbeginkwdNode2, pbeblockNode3, teolNode4);
        }
	nodeList.add(pbeginblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AEndblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PEndblock pendblockNode1;
        {
            // Block
        TEndkwd tendkwdNode2;
        PBeblock pbeblockNode3;
        LinkedList listNode5 = new LinkedList();
        tendkwdNode2 = (TEndkwd)nodeArrayList1.get(0);
        pbeblockNode3 = (PBeblock)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pendblockNode1 = new AEndblock(tendkwdNode2, pbeblockNode3, listNode5);
        }
	nodeList.add(pendblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AAbeblock1Beblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBeblock pbeblockNode1;
        {
            // Block
        TLcurly tlcurlyNode2;
        TSpace tspaceNode3;
        TChar tcharNode4;
        TSpace tspaceNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TRcurly trcurlyNode7;
        tlcurlyNode2 = (TLcurly)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        tcharNode4 = (TChar)nodeArrayList3.get(0);
        tspaceNode5 = (TSpace)nodeArrayList4.get(0);
        trcurlyNode7 = (TRcurly)nodeArrayList5.get(0);

        pbeblockNode1 = new ABeblock(tlcurlyNode2, tspaceNode3, tcharNode4, tspaceNode5, null, trcurlyNode7);
        }
	nodeList.add(pbeblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce AAbeblock2Beblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBeblock pbeblockNode1;
        {
            // Block
        TLcurly tlcurlyNode2;
        TSpace tspaceNode3;
        TChar tcharNode4;
        TSpace tspaceNode5;
        PBeblockv1 pbeblockv1Node6;
        TRcurly trcurlyNode7;
        tlcurlyNode2 = (TLcurly)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        tcharNode4 = (TChar)nodeArrayList3.get(0);
        tspaceNode5 = (TSpace)nodeArrayList4.get(0);
        pbeblockv1Node6 = (PBeblockv1)nodeArrayList5.get(0);
        trcurlyNode7 = (TRcurly)nodeArrayList6.get(0);

        pbeblockNode1 = new ABeblock(tlcurlyNode2, tspaceNode3, tcharNode4, tspaceNode5, pbeblockv1Node6, trcurlyNode7);
        }
	nodeList.add(pbeblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce ABeblockv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBeblockv1 pbeblockv1Node1;
        {
            // Block
        TPipe tpipeNode2;
        TChar tcharNode3;
        TSpace tspaceNode4;
        tpipeNode2 = (TPipe)nodeArrayList1.get(0);
        tcharNode3 = (TChar)nodeArrayList2.get(0);
        tspaceNode4 = (TSpace)nodeArrayList3.get(0);

        pbeblockv1Node1 = new ABeblockv1(tpipeNode2, tcharNode3, tspaceNode4);
        }
	nodeList.add(pbeblockv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce ASettingblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PSettingblock psettingblockNode1;
        {
            // Block
        TSettingkwd tsettingkwdNode2;
        TLcurly tlcurlyNode3;
        PShortident pshortidentNode4;
        TSpace tspaceNode5;
        TPipe tpipeNode6;
        TSpace tspaceNode7;
        TChar tcharNode8;
        TSpace tspaceNode9;
        TRcurly trcurlyNode10;
        TEol teolNode11;
        tsettingkwdNode2 = (TSettingkwd)nodeArrayList1.get(0);
        tlcurlyNode3 = (TLcurly)nodeArrayList2.get(0);
        pshortidentNode4 = (PShortident)nodeArrayList3.get(0);
        tspaceNode5 = (TSpace)nodeArrayList4.get(0);
        tpipeNode6 = (TPipe)nodeArrayList5.get(0);
        tspaceNode7 = (TSpace)nodeArrayList6.get(0);
        tcharNode8 = (TChar)nodeArrayList7.get(0);
        tspaceNode9 = (TSpace)nodeArrayList8.get(0);
        trcurlyNode10 = (TRcurly)nodeArrayList9.get(0);
        teolNode11 = (TEol)nodeArrayList10.get(0);

        psettingblockNode1 = new ASettingblock(tsettingkwdNode2, tlcurlyNode3, pshortidentNode4, tspaceNode5, tpipeNode6, tspaceNode7, tcharNode8, tspaceNode9, trcurlyNode10, teolNode11);
        }
	nodeList.add(psettingblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce APlains */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPlains pplainsNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pplainsNode1 = new APlains(listNode3);
        }
	nodeList.add(pplainsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AShortblockPlainsv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPlainsv1 pplainsv1Node1;
        {
            // Block
        PShortblock pshortblockNode2;
        pshortblockNode2 = (PShortblock)nodeArrayList1.get(0);

        pplainsv1Node1 = new AShortblockPlainsv1(pshortblockNode2);
        }
	nodeList.add(pplainsv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce ACharallPlainsv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPlainsv1 pplainsv1Node1;
        {
            // Block
        PCharall pcharallNode2;
        pcharallNode2 = (PCharall)nodeArrayList1.get(0);

        pplainsv1Node1 = new ACharallPlainsv1(pcharallNode2);
        }
	nodeList.add(pplainsv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AAshortblock1Shortblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortblock pshortblockNode1;
        {
            // Block
        TFormatKwd tformatkwdNode2;
        TLcurly tlcurlyNode3;
        TSpace tspaceNode4;
        @SuppressWarnings("unused") Object nullNode5 = null;
        PPlains pplainsNode6;
        TRcurly trcurlyNode7;
        tformatkwdNode2 = (TFormatKwd)nodeArrayList1.get(0);
        tlcurlyNode3 = (TLcurly)nodeArrayList2.get(0);
        tspaceNode4 = (TSpace)nodeArrayList3.get(0);
        pplainsNode6 = (PPlains)nodeArrayList4.get(0);
        trcurlyNode7 = (TRcurly)nodeArrayList5.get(0);

        pshortblockNode1 = new AShortblock(tformatkwdNode2, tlcurlyNode3, tspaceNode4, null, pplainsNode6, trcurlyNode7);
        }
	nodeList.add(pshortblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AAshortblock2Shortblock */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortblock pshortblockNode1;
        {
            // Block
        TFormatKwd tformatkwdNode2;
        TLcurly tlcurlyNode3;
        TSpace tspaceNode4;
        PShortidents pshortidentsNode5;
        PPlains pplainsNode6;
        TRcurly trcurlyNode7;
        tformatkwdNode2 = (TFormatKwd)nodeArrayList1.get(0);
        tlcurlyNode3 = (TLcurly)nodeArrayList2.get(0);
        tspaceNode4 = (TSpace)nodeArrayList3.get(0);
        pshortidentsNode5 = (PShortidents)nodeArrayList4.get(0);
        pplainsNode6 = (PPlains)nodeArrayList5.get(0);
        trcurlyNode7 = (TRcurly)nodeArrayList6.get(0);

        pshortblockNode1 = new AShortblock(tformatkwdNode2, tlcurlyNode3, tspaceNode4, pshortidentsNode5, pplainsNode6, trcurlyNode7);
        }
	nodeList.add(pshortblockNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AShortidents */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortidents pshortidentsNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        TPipe tpipeNode4;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        tpipeNode4 = (TPipe)nodeArrayList2.get(0);

        pshortidentsNode1 = new AShortidents(listNode3, tpipeNode4);
        }
	nodeList.add(pshortidentsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AShortident */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortident pshortidentNode1;
        {
            // Block
        PKwd pkwdNode2;
        TSpace tspaceNode3;
        TColon tcolonNode4;
        TSpace tspaceNode5;
        PShortidentv1 pshortidentv1Node6;
        TSpace tspaceNode7;
        pkwdNode2 = (PKwd)nodeArrayList1.get(0);
        tspaceNode3 = (TSpace)nodeArrayList2.get(0);
        tcolonNode4 = (TColon)nodeArrayList3.get(0);
        tspaceNode5 = (TSpace)nodeArrayList4.get(0);
        pshortidentv1Node6 = (PShortidentv1)nodeArrayList5.get(0);
        tspaceNode7 = (TSpace)nodeArrayList6.get(0);

        pshortidentNode1 = new AShortident(pkwdNode2, tspaceNode3, tcolonNode4, tspaceNode5, pshortidentv1Node6, tspaceNode7);
        }
	nodeList.add(pshortidentNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce ACharShortidentv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortidentv1 pshortidentv1Node1;
        {
            // Block
        TChar tcharNode2;
        tcharNode2 = (TChar)nodeArrayList1.get(0);

        pshortidentv1Node1 = new ACharShortidentv1(tcharNode2);
        }
	nodeList.add(pshortidentv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce ADigitShortidentv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PShortidentv1 pshortidentv1Node1;
        {
            // Block
        TDigit tdigitNode2;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);

        pshortidentv1Node1 = new ADigitShortidentv1(tdigitNode2);
        }
	nodeList.add(pshortidentv1Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AKwd */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PKwd pkwdNode1;
        {
            // Block
        TAtsign tatsignNode2;
        TChar tcharNode3;
        tatsignNode2 = (TAtsign)nodeArrayList1.get(0);
        tcharNode3 = (TChar)nodeArrayList2.get(0);

        pkwdNode1 = new AKwd(tatsignNode2, tcharNode3);
        }
	nodeList.add(pkwdNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce AColonCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TColon tcolonNode2;
        tcolonNode2 = (TColon)nodeArrayList1.get(0);

        pcharallNode1 = new AColonCharall(tcolonNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce ADigitCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TDigit tdigitNode2;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);

        pcharallNode1 = new ADigitCharall(tdigitNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce ASemicolonCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TScolon tscolonNode2;
        tscolonNode2 = (TScolon)nodeArrayList1.get(0);

        pcharallNode1 = new ASemicolonCharall(tscolonNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce APercentCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TPercent tpercentNode2;
        tpercentNode2 = (TPercent)nodeArrayList1.get(0);

        pcharallNode1 = new APercentCharall(tpercentNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce AForwardslashCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TFslash tfslashNode2;
        tfslashNode2 = (TFslash)nodeArrayList1.get(0);

        pcharallNode1 = new AForwardslashCharall(tfslashNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce ABackslashCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TBslash tbslashNode2;
        tbslashNode2 = (TBslash)nodeArrayList1.get(0);

        pcharallNode1 = new ABackslashCharall(tbslashNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AMorecharCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TMorechar tmorecharNode2;
        tmorecharNode2 = (TMorechar)nodeArrayList1.get(0);

        pcharallNode1 = new AMorecharCharall(tmorecharNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce ACharCharall */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCharall pcharallNode1;
        {
            // Block
        TChar tcharNode2;
        tcharNode2 = (TChar)nodeArrayList1.get(0);

        pcharallNode1 = new ACharCharall(tcharNode2);
        }
	nodeList.add(pcharallNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce ATerminal$Blocks */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PBlocks pblocksNode1;
        pblocksNode1 = (PBlocks)nodeArrayList1.get(0);
	if(pblocksNode1 != null)
	{
	  listNode2.add(pblocksNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce ANonTerminal$Blocks */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PBlocks pblocksNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pblocksNode2 = (PBlocks)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pblocksNode2 != null)
	{
	  listNode3.add(pblocksNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce ATerminal$Lines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PLines plinesNode1;
        plinesNode1 = (PLines)nodeArrayList1.get(0);
	if(plinesNode1 != null)
	{
	  listNode2.add(plinesNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce ANonTerminal$Lines */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PLines plinesNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        plinesNode2 = (PLines)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(plinesNode2 != null)
	{
	  listNode3.add(plinesNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce ATerminal$Eol */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        TEol teolNode1;
        teolNode1 = (TEol)nodeArrayList1.get(0);
	if(teolNode1 != null)
	{
	  listNode2.add(teolNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce ANonTerminal$Eol */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        TEol teolNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        teolNode2 = (TEol)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(teolNode2 != null)
	{
	  listNode3.add(teolNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce ATerminal$Plainsv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PPlainsv1 pplainsv1Node1;
        pplainsv1Node1 = (PPlainsv1)nodeArrayList1.get(0);
	if(pplainsv1Node1 != null)
	{
	  listNode2.add(pplainsv1Node1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ANonTerminal$Plainsv1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PPlainsv1 pplainsv1Node2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pplainsv1Node2 = (PPlainsv1)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pplainsv1Node2 != null)
	{
	  listNode3.add(pplainsv1Node2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce ATerminal$Shortident */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PShortident pshortidentNode1;
        pshortidentNode1 = (PShortident)nodeArrayList1.get(0);
	if(pshortidentNode1 != null)
	{
	  listNode2.add(pshortidentNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce ANonTerminal$Shortident */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PShortident pshortidentNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pshortidentNode2 = (PShortident)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pshortidentNode2 != null)
	{
	  listNode3.add(pshortidentNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {2, SHIFT, 1}, {3, SHIFT, 2}, },
			{{-1, ERROR, 1}, {6, SHIFT, 8}, },
			{{-1, ERROR, 2}, {6, SHIFT, 9}, },
			{{-1, ERROR, 3}, {20, ACCEPT, -1}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 5}, {0, SHIFT, 11}, {2, SHIFT, 1}, {4, SHIFT, 12}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {13, SHIFT, 17}, {14, SHIFT, 18}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 1}, {2, SHIFT, 1}, {3, SHIFT, 2}, },
			{{-1, ERROR, 8}, {5, SHIFT, 35}, },
			{{-1, ERROR, 9}, {1, SHIFT, 38}, },
			{{-1, ERROR, 10}, {16, SHIFT, 39}, },
			{{-1, ERROR, 11}, {6, SHIFT, 40}, },
			{{-1, ERROR, 12}, {6, SHIFT, 9}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 17}, {0, SHIFT, 11}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {13, SHIFT, 17}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, ERROR, 18}, {0, SHIFT, 11}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {14, SHIFT, 18}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 28}, {16, SHIFT, 48}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 32}, {0, SHIFT, 11}, {2, SHIFT, 1}, {4, SHIFT, 12}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {13, SHIFT, 17}, {14, SHIFT, 18}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 21}, {0, SHIFT, 11}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 35}, {17, SHIFT, 52}, },
			{{-1, ERROR, 36}, {1, SHIFT, 53}, },
			{{-1, ERROR, 37}, {1, SHIFT, 54}, },
			{{-1, ERROR, 38}, {17, SHIFT, 55}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 40}, {1, SHIFT, 56}, },
			{{-1, ERROR, 41}, {16, SHIFT, 57}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 44}, {16, SHIFT, 59}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 47}, {16, SHIFT, 60}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 53}, {8, SHIFT, 61}, },
			{{-1, ERROR, 54}, {11, SHIFT, 62}, },
			{{-1, ERROR, 55}, {1, SHIFT, 63}, },
			{{-1, ERROR, 56}, {0, SHIFT, 11}, {5, SHIFT, 35}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 16}, {16, SHIFT, 68}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 61}, {1, SHIFT, 69}, },
			{{-1, ERROR, 62}, {1, SHIFT, 70}, },
			{{-1, ERROR, 63}, {7, SHIFT, 71}, {8, SHIFT, 72}, },
			{{-1, ERROR, 64}, {7, SHIFT, 74}, },
			{{-1, ERROR, 65}, {0, SHIFT, 11}, {9, SHIFT, 13}, {10, SHIFT, 14}, {11, SHIFT, 15}, {12, SHIFT, 16}, {15, SHIFT, 19}, {17, SHIFT, 20}, {18, SHIFT, 21}, {19, SHIFT, 22}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 67}, {5, SHIFT, 35}, {8, SHIFT, 76}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 69}, {17, SHIFT, 78}, },
			{{-1, ERROR, 70}, {17, SHIFT, 79}, {18, SHIFT, 80}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 72}, {17, SHIFT, 82}, },
			{{-1, ERROR, 73}, {7, SHIFT, 83}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 75}, {7, SHIFT, 84}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 78}, {1, SHIFT, 85}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 81}, {1, SHIFT, 86}, },
			{{-1, ERROR, 82}, {1, SHIFT, 87}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 85}, {7, SHIFT, 88}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 88}, {16, SHIFT, 89}, },
			{{-1, REDUCE, 20}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, {7, 34}, },
			{{-1, 23}, {32, 49}, },
			{{-1, 24}, {18, 45}, },
			{{-1, 46}, },
			{{-1, 25}, {17, 42}, },
			{{-1, 43}, },
			{{-1, 5}, },
			{{-1, 26}, {32, 50}, },
			{{-1, 10}, {12, 41}, },
			{{-1, 73}, },
			{{-1, 6}, {5, 27}, {32, 27}, },
			{{-1, 28}, {17, 44}, {18, 47}, {56, 64}, {65, 75}, },
			{{-1, 29}, {33, 51}, },
			{{-1, 30}, },
			{{-1, 65}, },
			{{-1, 36}, {56, 66}, {67, 77}, },
			{{-1, 81}, },
			{{-1, 37}, },
			{{-1, 31}, },
			{{-1, 7}, },
			{{-1, 32}, },
			{{-1, 58}, },
			{{-1, 33}, },
			{{-1, 67}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '@setting', '@begin', EOF",
			"expecting: '{'",
			"expecting: EOF",
			"expecting: format kwd, '@setting', '@end', '/', '\', ':', ';', '*', '#', '%', char, digit, morechar",
			"expecting: '@'",
			"expecting: space",
			"expecting: eol",
			"expecting: format kwd, '}', '/', '\', ':', ';', '%', eol, char, digit, morechar",
			"expecting: format kwd, '/', '\', ':', ';', '*', '%', char, digit, morechar",
			"expecting: format kwd, '/', '\', ':', ';', '#', '%', char, digit, morechar",
			"expecting: char",
			"expecting: '|'",
			"expecting: ':'",
			"expecting: format kwd, '@', '/', '\', ':', ';', '%', char, digit, morechar",
			"expecting: '@setting', '@begin', eol, EOF",
			"expecting: '}', '|'",
			"expecting: '}'",
			"expecting: format kwd, '/', '\', ':', ';', '%', char, digit, morechar",
			"expecting: '@', '|'",
			"expecting: char, digit",
			"expecting: space, '@', '|'",
			"expecting: format kwd, '@setting', '@begin', '@end', '/', '\', ':', ';', '*', '#', '%', char, digit, morechar, EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 0, 3, 0, 0, 4, 5, 6, 1, 1, 7, 7, 7, 7, 8, 9, 7, 7, 7, 7, 3, 3, 3, 0, 3, 6, 7, 7, 7, 3, 7, 0, 10, 5, 5, 10, 3, 5, 6, 3, 3, 6, 3, 3, 6, 3, 3, 0, 7, 5, 11, 12, 5, 13, 14, 14, 3, 3, 5, 5, 15, 16, 17, 18, 18, 14, 10, 19, 6, 10, 16, 7, 16, 17, 18, 5, 5, 5, 5, 5, 6, 7, 16, 20, 16, 6, 21, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
